### PR TITLE
Allow setting of runtime in pyauditor Record

### PR DESCRIPTION
**Pull request by stefan-k**

### CODE REVIEW

**Review by dirksammel — COMMENTED** [review]
Is this what we discussed yesterday? I thought the solution would be to automatically fill the `runtime` attribute of a record when the stop_time is added (if that is even possible).

**Comment by stefan-k** [comment]
I thought that we came to another conclusion ;) 
It's possible to calculate it when stop_time is set, but it may create the impression that this is the value that is being sent to Auditor, which is not the case. Of course the value computed locally and the one computed remotely should be the same but one never knows. 
But I think I'll change it to compute it automatically.

**Comment by dirksammel** [comment]
>but it may create the impression that this is the value that is being sent to Auditor, which is not the case
but what value is finally sent to Auditor?

**Comment by stefan-k** [comment]
> but what value is finally sent to Auditor?

No value is sent, Auditor calculates this value itself from `start_time` and `stop_time`. The reasoning is that this way there cannot be inconsistencies between start/stop time and runtime. Of course we can prevent inconsistencies via the official clients, but we can't prevent inconsistencies when using curl for instance.

**Comment by stefan-k** [comment]
> wouldn't this be a solution:

Have you read my previous comment?

**Comment by dirksammel** [comment]
> Have you read my previous comment?
yes, but it seems I don't understand how it is currently done and how there can be any inconsistencies

**Comment by stefan-k** [comment]
If the runtime is calculated on the client side, as you suggested, it is the responsibility of the client to correctly calculate the runtime.
Your suggestion only works if only the official clients are used (because there we control the code). However, it is possible to send records directly to the API using JSON encoded records. What if someone sets runtime to an incorrect value? How should we treat that on the server side? If we reject those records, we might as well calculate runtime at the server side. If we correct the value of runtime on the server side, why even bother calculating it on the client side? If we just ignore it and accept wrong values, how are the plugins supposed to deal with inconsistencies?

The only point where we can ensure that records meet certain quality standards is in the Auditor server. 

The runtime is special in the sense that it is the only redundant information in the Record. Due to start and stop time it is actually not needed. The intention was to have one "source of true runtime", which is the Auditor server, and to avoid that plugins have to calculate that value. 

Runtime is now calculated when adding a stop_time, but it will not be sent to Auditor. Given that both server and client use the same code, I hope that the values on client and server will be equivalent.

**Pull request merged**
