### PR TITLE
Update compare-link to version of latest release in CHANGELOG.

### PR DESCRIPTION
**Pull request by rfvc**
This updates the "Unreleased" compare view link to the latest release `v0.1.0`

### CODE REVIEW

**Comment by QuantumDancer** [comment]
Hi @rfvc, thanks for this PR. I think this is ready for review, right? If yes, could you remove the draft status so that I can merge it? Thanks!

**Comment by rfvc** [comment]
> Hi @rfvc, thanks for this PR. I think this is ready for review, right? If yes, could you remove the draft status so that I can merge it? Thanks! 

Hey @QuantumDancer, yes and no. This PR is ready for review, though one (completely unrelated) test is failing and I didn't have time to check why. Feel free to look into this!

**Comment by rfvc** [comment]
I just saw you added the `Release v0.2.0`-milestone. For this we should change this again, though 😅

**Comment by QuantumDancer** [comment]
> > Hi @rfvc, thanks for this PR. I think this is ready for review, right? If yes, could you remove the draft status so that I can merge it? Thanks!
> 
> Hey @QuantumDancer, yes and no. This PR is ready for review, though one (completely unrelated) test is failing and I didn't have time to check why. Feel free to look into this!

The `pyauditor / pyauditor tests` workflow sometimes fails without reason. Usually a restart (or multiple restarts) solve this problem. We are aware of this problem and also did some debugging (see #176) but unfortunately couldn't find the root cause for this issue yet.

**Comment by QuantumDancer** [comment]
> I just saw you added the `Release v0.2.0`-milestone. For this we should change this again, though 😅

Yes sure. I just added it to the release to keep track of PRs/issues that we want to have closed before the release. When creating the release, we will then update it again.

**Review by QuantumDancer — APPROVED** [review]

**Comment by rfvc** [comment]
Alright, thanks! 🙂

**Pull request merged**
